# Generated by Django 2.2.2 on 2019-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
