# Generated by Django 2.2.2 on 2019-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_atualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
