# Generated by Django 2.2.2 on 2019-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_categoria_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
