# Generated by Django 2.2.2 on 2019-06-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0002_auto_20190617_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cep',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='whatsapp',
            field=models.BigIntegerField(),
        ),
    ]
