# Generated by Django 2.2.2 on 2019-06-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0004_auto_20190618_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='categoria',
        ),
    ]
