# Generated by Django 2.2.2 on 2019-06-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_atualizado'),
        ('estabelecimento', '0005_remove_estabelecimento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='categoria',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='categoria.Categoria'),
            preserve_default=False,
        ),
    ]
