# Generated by Django 2.2.2 on 2019-06-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0006_estabelecimento_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.Categoria'),
        ),
    ]
