# Generated by Django 2.2.2 on 2019-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0007_auto_20190618_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
