# Generated by Django 2.2.2 on 2019-06-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0009_auto_20190619_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='categoria.Categoria'),
        ),
    ]
